apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-notes-vitepress
  labels:
    app: code-notes-vitepress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-notes-vitepress
  template:
    metadata:
      labels:
        app: code-notes-vitepress
    spec:
      containers:
        - name: code-notes-vitepress
          image: hub.lubui.com/code-notes-vitepress:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: code-notes-vitepress
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: code-notes-vitepress
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: code-notes-vitepress
spec:
  tls:
    secretName: tls-lubui.com
  entryPoints:
    - websecure
  routes:
    - match: Host(`lubui.com`)||Host(`www.lubui.com`)
      kind: Rule
      services:
        - name: code-notes-vitepress
          port: 80
